services:
  nginx:
    image: nginx:1.29.3-trixie-perl
    restart: unless-stopped
    expose:
      - 80
      - 443
    volumes:
      - ./nginx:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      internal_net:
        ipv4_address: ${PRIVATE_NGINX_ADDRESS}
    environment:
      - PRIVATE_WIREGUARD_ADDRESS=${PRIVATE_WIREGUARD_ADDRESS}
      - SSL_PORT=${SSL_PORT}
      - MINIO_API_SUBDOAMIN=${MINIO_API_SUBDOMAIN}
      - MINIO_SUBDOAMIN=${MINIO_SUBDOMAIN}
      - VAULTWARDEN_SUBDOAMIN=${VAULTWARDEN_SUBDOMAIN}
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
    depends_on:
      - vaultwarden

  vaultwarden:
    image: vaultwarden/server:testing
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.ikerketa.com"
      SIGNUPS_ALLOWED: false
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
    networks:
      internal_net:
        ipv4_address: ${PRIVATE_VAULTWARDEN_ADDRESS}
    volumes:
      - ./vaultwarden/vw-data/:/data/

  minio:
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z
    volumes:
      - ./minio/data:/mnt/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: https://s3-api.ikerketa.com
      MINIO_BROWSER_REDIRECT_URL: https://s3.ikerketa.com
      MINIO_BROWSER_ENABLE_LICENSING: off
    networks:
      internal_net:
        ipv4_address: ${PRIVATE_MINIO_ADDRESS}
    command: server /mnt/minio --console-address ":9001"

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    networks:
      internal_net:
        ipv4_address: ${PRIVATE_WIREGUARD_ADDRESS}
    environment:
      - PRIVATE_COREDNS_ADDRESS=${PRIVATE_COREDNS_ADDRESS}
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=vpn.ikerketa.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=${PRIVATE_COREDNS_ADDRESS}
      - INTERNAL_SUBNET=10.42.24.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  coredns:
    image: coredns/coredns:1.13.1
    restart: unless-stopped
    environment:
      - PRIVATE_NGINX_ADDRESS=${PRIVATE_NGINX_ADDRESS}
    networks:
      internal_net:
        ipv4_address: ${PRIVATE_COREDNS_ADDRESS}
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile:ro
    command: -conf /etc/coredns/Corefile
  
networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${PRIVATE_NETWORK_ADDRESS}