services:
  certbot:
    image: certbot-hetzner
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./conf:/conf
    env_file:
      - .env
    command: >
      certonly 
        --manual 
        --preferred-challenges=dns 
        --manual-auth-hook /scripts/auth.sh 
        --manual-cleanup-hook /scripts/cleanup.sh 
        -d ${DOMAIN} 
        -d *.${DOMAIN} 
        -vv
