server {
    listen 80;
    server_name vw.ikerketa.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name vw.ikerketa.com;

    allow 172.18.0.0/24;
    deny all;

    ssl_certificate     /etc/letsencrypt/live/ikerketa.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ikerketa.com/privkey.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://vaultwarden:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

